# --- !Ups

create table "tasks" (
  id bigint generated by default as identity(start with 1) not null primary key,
  name varchar(255) NOT NULL,
  description varchar(255) NOT NULL,
  category varchar(255) NOT NULL,
  dueDate datetime,
  createDate datetime
);

# --- !Downs

DROP TABLE Tasks;
